### PR TITLE
Fix undefined behavior in Halo::exchangeVectorInt

### LINKED ISSUE #317: GCC 15 flags out-of-bounds access
When running Omega built with GCC 15, I'm getting errors of this kind:
```
/usr/include/c++/15/bits/stl_vector.h:1263: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = int; _Alloc = std::allocator<int>; reference = int&
; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
```
This happens, for example, when I run the `ocean/planar/barotropic_gyre` problem on 16 MPI ranks.

The error is triggered by [components/omega/src/base/Halo.cpp:629](https://github.com/E3SM-Project/Omega/blob/1ba277817a602abfaad4d6faaa7363eab70fc1c7/components/omega/src/base/Halo.cpp#L629) and [components/omega/src/base/Halo.cpp:641](https://github.com/E3SM-Project/Omega/blob/1ba277817a602abfaad4d6faaa7363eab70fc1c7/components/omega/src/base/Halo.cpp#L641). The problem seems to be that the size of `RecvVec[INghbr]` is 0 in this case. While we tell MPI to send data of size 0, so it won't cause any failure, this still triggers GCC's error because we use `&RecvVec[INghbr][0]` to get the address of the beginning of the vector. The `[0]` part is [undefined behavior](https://en.cppreference.com/w/cpp/container/vector/operator_at.html), so it's probably good to replace it even though it likely didn't do any harm before the GCC 15 error message.

I think the correct solution is to use `.data()` instead. I have a PR ready.

### PR DESCRIPTION
**Pull request by tukss**
Taking `[0]` of a vector of size 0 is undefined behavior in C++ and causes assertion errors in GCC >= 15. The data method also gives a pointer to the data but is not UB as long as it is not dereferenced.

This should not change the behavior of the code in any way as we always called the MPI functions with a zero size. It just avoids the UB and the associated GCC error.

Fixes #317.

### CODE REVIEW

File: components/omega/src/base/Halo.cpp [hunk 1]
```diff
@@ -624,10 +624,10 @@ int Halo::exchangeVectorInt(
    std::vector<MPI_Request> SendReqs(NNghbr);
 
    for (int INghbr = 0; INghbr < NNghbr; ++INghbr) {
-      I4 DimLen = RecvVec[INghbr].size();
-      RecvErr[INghbr] =
-          MPI_Irecv(&RecvVec[INghbr][0], DimLen, MPI_INT, NeighborList[INghbr],
-                    MPI_ANY_TAG, MyComm, &RecvReqs[INghbr]);
+      I4 DimLen       = RecvVec[INghbr].size();
```
Comment (tukss) [inline components/omega/src/base/Halo.cpp:627]: There was no need to touch this line but I needed to change the spacing to keep `clang-format` happy.

**Review by mwarusz — APPROVED** [review]
LGTM. Since this is a very simple change, I only verified that CTests pass on my work laptop.

**Comment by brian-oneill** [comment]
I ran the ctests successfully on pm-cpu, pm-gpu and Frontier cpu & gpu. Looks good.

**Review by brian-oneill — APPROVED** [review]
