### PR TITLE
Vertical coordinate updates and fixes

### LINKED ISSUE #290: During testing, CTest reports warnings originating from `VertCoord.cpp`
Omega CTest produces the following warnings from `VertCoord.cpp`:
```
[warning] [VertCoord.cpp:70] VertCoord: error reading nVertLevels from mesh file, using NVertLayers = 1
[warning] [VertCoord.cpp:163] VertCoord: Error reading InitialVertCoord stream
[warning] [VertCoord.cpp:172] VertCoord: Error reading minLevelCell from InitialVertCoord, using MinLayerCell = 0
```
These warnings may or may not be valid, so I’m creating this issue to raise awareness and start a discussion.

### PR DESCRIPTION
**Pull request by brian-oneill**
This PR implements fixes, additions, and refactoring for the vertical coordinate module, including:
- Moving `EdgeMask` from `HorzMesh` to `VertCoord`, and fixing initialization so `EdgeMask` properly accounts for bathymetry
- This change removes the need for bootstrapping the `VertCoord`, initialization is consolidated into a single `VertCoord::init()` method
- Replacing `LOG_WARN` messages with `LOG_INFO` during construction
- Adding support for both new Omega names and old MPAS names when reading `NVertLayers`, `MaxLayerCell`, and `MinLayerCell` from mesh file
- Adding optional arguments to `VertCoord::init()` to enhance flexibility in unit tests
- Adding `CellMask` and `VertexMask` arrays for potential future use
- Introducing new mask tests to the `VertCoord` unit test

Ctests were run successfully on Frontier CPU & GPU, pm-cpu, pm-gpu, and Chrysalis

Fixes #290 

Checklist
* [x] Documentation:
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [x] Building
  * [x] CMake build does not produce any new warnings from changes in this PR
* [x] Testing
  * [x] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [x] CTest unit tests for new features have been added per the approved design.
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

File: components/omega/src/infra/IOStream.cpp [hunk 1]
```diff
@@ -1645,6 +1645,15 @@ Error IOStream::readFieldData(
    }
    // For back compatibility, try to read again with old field name
    if (Err.isFail()) {
+      // Check for "Layer" in string, backwards compatibility requires replacing
```
Comment (philipwjones) [inline components/omega/src/infra/IOStream.cpp]: Can we move this replacement up just after OldFieldName is defined? That keeps all the renaming in one place.

Also, we don't need to Log the change so I'd remove LOG_INFO call.

**Review by philipwjones — APPROVED** [review]
Looks good. Just had one minor suggestion below. Also verified it passes unit tests.

File: components/omega/src/infra/IOStream.cpp (hunk 1 above)
Comment (brian-oneill) [reply components/omega/src/infra/IOStream.cpp]: Oops, didn't mean to leave the `LOG_INFO` call in there, was just for debugging. 

My thinking was to not do the find and replace unless necessary, but I suppose our field names are small enough that it's basically negligible.

File: components/omega/src/ocn/AuxiliaryState.h [hunk 2]
```diff
@@ -82,13 +83,15 @@ class AuxiliaryState {
                    int TimeLevel) const;
 
  private:
-   AuxiliaryState(const std::string &Name, const HorzMesh *Mesh, Halo *MeshHalo,
-                  int NVertLayers, int NTracers);
+   AuxiliaryState(const std::string &Name, const HorzMesh *Mesh,
+                  const VertCoord *VCoord, Halo *MeshHalo, int NVertLayers,
```
Comment (mwarusz) [inline components/omega/src/ocn/AuxiliaryState.h:87]: Now that you passing in an instance of `VertCoord` you could remove the  `NVertLayers` argument.

File: components/omega/src/ocn/auxiliaryVars/TracerAuxVars.cpp [hunk 3]
```diff
@@ -6,16 +6,16 @@
 namespace OMEGA {
 
 TracerAuxVars::TracerAuxVars(const std::string &AuxStateSuffix,
-                             const HorzMesh *Mesh, const I4 NVertLayers,
-                             const I4 NTracers)
+                             const HorzMesh *Mesh, const VertCoord *VCoord,
+                             const I4 NVertLayers, const I4 NTracers)
```
Comment (mwarusz) [inline components/omega/src/ocn/auxiliaryVars/TracerAuxVars.cpp:10]: Same as in the `AuxiliaryState`, there is now no need to pass `NVertLayers` separately. This comment applies also to the other auxiliary vars that had similar changes.

File: components/omega/src/ocn/VertCoord.cpp [hunk 4]
```diff
@@ -23,53 +23,101 @@ VertCoord *VertCoord::DefaultVertCoord = nullptr;
...
 //------------------------------------------------------------------------------
-// Construct a new VertCoord instance given a Decomp. New object is incomplete
-// and completeSetup must be called afterwards
+// Construct a new VertCoord instance given a Decomp.
 VertCoord::VertCoord(const std::string &Name_, //< [in] Name for new VertCoord
-                     const Decomp *Decomp      //< [in] associated Decomp
+                     const Decomp *Decomp,     //< [in] associated Decomp
+                     Config *Options,          //< [in] configuration options
+                     const bool ReadStream,    //< [in] logical to read stream
+                     const int InNVertLayers   //< [in] int to set vertical dim
```
Comment (mwarusz) [inline components/omega/src/ocn/VertCoord.cpp:58]: Is it valid to have `ReadStream = true` and non-zero `InVertLayers` ? If not, can we check for this case and abort ?

File: components/omega/src/ocn/VertCoord.cpp [hunk 5]
```diff
@@ -23,53 +23,101 @@ VertCoord *VertCoord::DefaultVertCoord = nullptr;
...
+
+   if (MovementWeightStr == "Fixed") {
+      MvmtWgtChoice = MovementWeightType::Fixed;
+   } else if (MovementWeightStr == "Uniform") {
+      MvmtWgtChoice = MovementWeightType::Uniform;
+   } else {
+      ABORT_ERROR("VertCoord: Unknown MovementWeightType requested");
+   }
+
+   // Fetch reference desnity from Config
```
Comment (mwarusz) [inline components/omega/src/ocn/VertCoord.cpp]:
```suggestion
   // Fetch reference density from Config
```

**Review by mwarusz — COMMENTED** [review]
The changes look mostly good. I left a couple of small comments.

However, I ran the test suite on pm-cpu with Kokkos bounds checking turned on and got many fails. They all look like this:
```
1: Kokkos::View ERROR: out of bounds access label=("VertexMask") with indices [1008,16] but extents [1169,16]
```
Specifically the following tests failed:
```
         13 - AUXVARS_PLANE_TEST (Failed)
         14 - AUXVARS_SPHERE_TEST (Failed)
         15 - AUXSTATE_TEST (Failed)
         20 - TEND_PLANE_TEST (Failed)
         21 - TEND_PLANE_SINGLE_PRECISION_TEST (Failed)
         22 - TEND_SPHERE_TEST (Failed)
         23 - TENDENCIES_TEST (Failed)
         27 - TIMESTEPPER_TEST (Failed)
         31 - TRACERS_TEST (Failed)
         34 - EOS_TEST (Failed)
```

I looked into the failures a little bit and I think they might be related to how the `MaxLayerCell` array is set in the case of prescribed `NVertLayers`. Because `deepCopy` is used, the value of `MaxLayerCell(NCellsAll)` is set to `NVertLayers`, but then never adjusted for 0-based indexing. I am not sure if this element should be set at all, or just be zero.

I have one more suggestion related to an issue I ran into when testing my hierarchical parallelism changes. I believe that currently when the `MinLayerCell` and `MaxLayerCell` arrays are read through iostreams they do not have their halo regions filled. So even thought the computations of the other Min/Max arrays and masks are done for all elements, they do not contain valid values everywhere. @brian-oneill Do you think it makes sense to fix this as part of this PR ?

**Comment by brian-oneill** [comment]
> I looked into the failures a little bit and I think they might be related to how the `MaxLayerCell` array is set in the case of prescribed `NVertLayers`. Because `deepCopy` is used, the value of `MaxLayerCell(NCellsAll)` is set to `NVertLayers`, but then never adjusted for 0-based indexing. I am not sure if this element should be set at all, or just be zero.

Thanks for catching this. Actually, I meant to set `MaxLayerCell(NCellsAll) = -1`, but neglected to initially. The connectivity arrays use `N----All` to signify inactive elements (for example, `CellsOnEdge` on a boundary edge will return `NCellsAll` for one of the cells). This points to the last element of the `MaxLayer----` arrays.

Setting `MaxLayerCell(NCellsAll) = -1` ensures the vertical loop is skipped (since `kmax < kmin`), which matches how this was handled in MPAS, just adjusted here for 0-based indexing. I'm definitely open to suggestions if you have other ideas.

**Comment by brian-oneill** [comment]
> I have one more suggestion related to an issue I ran into when testing my hierarchical parallelism changes. I believe that currently when the `MinLayerCell` and `MaxLayerCell` arrays are read through iostreams they do not have their halo regions filled. So even thought the computations of the other Min/Max arrays and masks are done for all elements, they do not contain valid values everywhere. @brian-oneill Do you think it makes sense to fix this as part of this PR ?
 
Thanks, I made edits to exchange the halos for all the min/max arrays

File: components/omega/src/ocn/AuxiliaryState.h (hunk 2 above)
Comment (brian-oneill) [reply components/omega/src/ocn/AuxiliaryState.h:87]: Looks like you're handling these in the new PR you just made, so I'll leave these alone for now

File: components/omega/src/ocn/VertCoord.cpp (hunk 4 above)
Comment (brian-oneill) [reply components/omega/src/ocn/VertCoord.cpp:58]: Done

File: components/omega/src/ocn/VertCoord.cpp (hunk 5 above)
Comment (brian-oneill) [reply components/omega/src/ocn/VertCoord.cpp]: Fixed

File: components/omega/src/ocn/VertCoord.cpp [hunk 6]
```diff
@@ -478,10 +455,127 @@ void VertCoord::clear() {
...
+       {NCellsAll}, KOKKOS_LAMBDA(int ICell) {
+          LocMinLayerCell(ICell) -= 1;
+          LocMaxLayerCell(ICell) -= 1;
+       });
+
+   // Exchange halos since stream only reads owned cells
+   MeshHalo->exchangeFullArrayHalo(MinLayerCell, OnCell);
+   MeshHalo->exchangeFullArrayHalo(MaxLayerCell, OnCell);
+
+   // The index ICell = NCellsAll is represents an inactive cell
```
Comment (mwarusz) [inline components/omega/src/ocn/VertCoord.cpp]:
```suggestion
   // The index ICell = NCellsAll  represents an inactive cell
```

**Review by mwarusz — APPROVED** [review]
Aside from one small typo in a comment, this looks good to me now. The ctests passed on pm-cpu, pm-gpu and frontier-gpu. Thanks @brian-oneill !

**Review by cbegeman — APPROVED** [review]
@brian-oneill Looks great! Thanks for making these changes. We agreed that this issue https://github.com/E3SM-Project/Omega/issues/321 will be addressed in a separate PR.

**Comment by mark-petersen** [comment]
Tested the rebased branch on perlmutter cpu and gpu. Passes all ctests.
