### PR TITLE
Halo fixes and updates

### LINKED ISSUE #51: Segmentation fault in Halo tests
For certain combinations of meshes and number of tasks I get segmentation faults when running the halo exchange test.

The segfaults happen inside the `Halo` constructor usually on the second call to the `generateExchangeLists` method (i.e. for edges).  I tracked this down to an out of bounds access in the following lines:
https://github.com/E3SM-Project/Omega/blob/3f7369496150cca1162365cfac0eebbd55a41cd9/components/omega/src/base/Halo.cpp#L281-L283

because of invalid `INghbr` index.

This index is invalid when the search on line 281 fails. That in turn happens because for certain decompositions the task id stored in `EdgeLoc` is not found in `NeighborList`, which is constucted only once based on `CellLoc`. I am not sure if this a problem with the halo construction or the decomposition.

This issue can be reproduced on Chrysalis by running the Halo update test with
- 4 tasks using the `ocean.QU.480km.151209.nc` mesh
- 12 tasks using the `ocean.QU.240km.151209.nc` mesh

### PR DESCRIPTION
**Pull request by brian-oneill**
Some updates and bug fixes for the Halo class:

- Creates static pointer DefaultHalo and static map AllHalos, along with init, accessor, and cleanup methods, for easy access to default Halo and any other defined Halo objects, and consistency with design of other Omega classes
- Fixes determination of neighboring tasks during Halo construction for decompositions where tasks need to exchange halo elements in just the edge or vertex index spaces and not the cell index space or when only a one-sided exchange is needed
- Replaces MPI blocking routines that were causing deadlock in some cases with non-blocking routines

Checklist
* [x] Documentation:
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [x] Testing
  * [x] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.
 

Fixes #51 
~~NOTE: There are still segmentation faults that can occur running testHalo.exe with higher task counts on the QU240 and QU120 meshes (e.g. running on Chrysalis with QU240 mesh and 470 tasks). This crash occurs during buffer packs and is a separate failure point from #51. I'll keep looking into resolving these crashes.~~
Resolved this error, have run testHalo.exe on QU240 mesh with up to 2048 tasks on Chrysalis without failure.

### CODE REVIEW

File: components/omega/src/base/Halo.h [hunk 1]
```diff
@@ -265,52 +317,66 @@ class Halo {
          TotSize *= Array.extent(NDims - 1);
       }
 
+      // Synchronize all tasks before starting communication
+      MPI_Barrier(MyComm);
```
Comment (philipwjones) [inline components/omega/src/base/Halo.h:321]: Is this barrier needed?  Ok if it is, just don't want to introduce any unnecessary sync points.

**Review by philipwjones — APPROVED** [review]
Other than the comment on the barrier, this looks good. Also verified unit tests pass on Chrysalis, Frontier (cpu and gpu). Doc changes are good and verified doc build too.

File: components/omega/src/base/Halo.h (hunk 1 above)
Comment (brian-oneill) [reply components/omega/src/base/Halo.h:321]: I can remove it. I do kinda worry about race conditions that might occur with sequential exchanges one right after another, since the same buffers are used for each exchange, but nothing specific has popped up in tests so far. Can hold off on any extra sync points for now.

Comment (philipwjones) [reply components/omega/src/base/Halo.h:321]: Thanks - I understand the worry but if we have the proper barriers/waits after the messages and the subroutine exit ensures the buffer has been copied into the proper place, we should be ok.

Comment (philipwjones) [reply components/omega/src/base/Halo.h:321]: Slight clarification of that - we'll need to watch out for cases where we need kokkos fences too since a parallelFor is asynchronous.

**Review by mwarusz — APPROVED** [review]
Verified that unit tests pass and that halo tests work with different numbers of mpi tasks on pm-cpu . Changes look good. Thanks @brian-oneill.

**Review by sbrus89 — APPROVED** [review]
These changes look good to me. Thanks @brian-oneill!
